---
title: "Guseinov_Fiscal"
output: html_document
date: "2025-09-24"
---

```{r, packages}
p_needed <- c("dplyr", "ggplot2", "countrycode", "wpp2024", "vdemdata", "tidyr", "PanelMatch", "readxl", "states", "slider", "brglm2", "clubSandwich", "stargazer", "marginaleffects")
packages <- rownames(installed.packages())
p_to_install <- p_needed[!(p_needed %in% packages)]
if (length(p_to_install) > 0) {
  install.packages(p_to_install)
}
sapply(p_needed, require, character.only = TRUE)
set.seed(666)
options(warn = -1)
```

```{r, load revolutions data}
NAVCO1.3_default <- read.csv("NAVCO1.3_default .csv") # NAVCO 1.3 event structure
NAVCO1.3_default <- NAVCO1.3_default %>%
  dplyr::mutate(cow = countrycode(LOCATION, "country.name", "cown")) %>%
  dplyr::mutate(cow = case_when(
    LOCATION == "Serbia" ~ 345,
    LOCATION == "Western Sahara" ~ 600,
    TRUE ~ cow
  )) %>%
  dplyr::rename(
    year = BYEAR,
    NVC1.3_EYEAR = EYEAR,
    NVC1.3_campaignname = CAMPAIGNNAME
  ) %>%
  dplyr::select(!c(LOCATION, NVC1.3_campaignname))

NAVCO2.1_regr <- read.csv("NAVCO2.1_regr.csv", sep = ",") # NAVCO 2.1 event structure
NAVCO2.1_regr <- NAVCO2.1_regr %>%
  dplyr::rename(
    cow = NVC2.1_loc_cow,
    year = NVC2.1_start_year, end_year = NVC2.1_end_year, NVC2.1_event_name = NVC2.1_camp_name
  ) %>%
  dplyr::mutate(
    cow = as.numeric(cow),
    NVC2.1_location = countrycode(cow, "cown", "country.name"),
    NVC2.1_VIOL = ifelse(NVC2.1_prim_meth == 0, 1, 0),
    NVC2.1_NONVIOL = ifelse(NVC2.1_prim_meth == 1, 1, 0)
  ) %>%
  mutate(cow = ifelse(NVC2.1_location == "Serbia", 345, cow)) %>% # new
  drop_na(cow) %>%
  filter(cow > 0) %>%
  dplyr::select(!c(NVC2.1_location, NVC2.1_id, NVC2.1_prim_meth, NVC2.1_progress, NVC2.1_event_name, end_year))

beis_regr <- read.csv("beis_regr.csv", sep = ";")
beis_regr <- beis_regr %>%
  mutate(cow = ifelse(beis_cowcode > 990, beis_cowmetrocode, beis_cowcode)) %>%
  mutate(
    cow = as.numeric(cow),
    beis_failure = ifelse(beis_success == 0, 1, 0),
    beis_unarmed = ifelse(beis_armed == 0, 1, 0)
  ) %>%
  dplyr::rename(year = beis_startyear, end_year = beis_endyear, event_name = beis_nameofrevolution) %>%
  dplyr::select(!c(beis_cowcode, beis_cowmetrocode, beis_isoabb, end_year))


csra <- read_excel("csra.xlsx")
csra <- csra %>%
  dplyr::mutate(year = start_year, cow = countrycode(country, "country.name", "cown")) %>%
  rename_with(
    .cols = c(successful:all),
    .fn = ~ paste0("csra_", .)
  ) %>%
  dplyr::mutate(cow = case_when(
    country == "Serbia" ~ 345,
    country == "Western Sahara" ~ 600,
    TRUE ~ cow
  )) %>%
  dplyr::select(cow, year, starts_with("csra_"))

beis_regr_2000 <- beis_regr %>%
  dplyr::rename(csra_armed = beis_armed, csra_unarmed = beis_unarmed) %>%
  filter(year <= 1999) %>%
  dplyr::select(cow, year, csra_armed, csra_unarmed)

nvc1.3_regr_2000 <- NAVCO1.3_default %>%
  dplyr::rename(csra_armed = NVC1.3_VIOL, csra_unarmed = NVC1.3_NONVIOL) %>%
  filter(year <= 1999) %>%
  dplyr::select(cow, year, csra_armed, csra_unarmed)

nvc2.1_regr_2000 <- NAVCO2.1_regr %>%
  dplyr::rename(csra_armed = NVC2.1_VIOL, csra_unarmed = NVC2.1_NONVIOL) %>%
  filter(year <= 1999) %>%
  dplyr::select(cow, year, csra_armed, csra_unarmed)

csra_2000 <- csra %>% dplyr::select(cow, year, csra_armed, csra_unarmed)
beis_csra <- bind_rows(beis_regr_2000, csra_2000)
nvc1.3_csra <- bind_rows(nvc1.3_regr_2000, csra_2000)
nvc2.1_csra <- bind_rows(nvc2.1_regr_2000, csra_2000)
```

```{r, other variables, include=FALSE}
data(pop1dt)
population <- pop1dt %>%
  dplyr::mutate(
    cow = countrycode(name, "country.name", "cown"),
    iso3c = countrycode(name, "country.name", "iso3c"),
    pop = round(pop)
  ) %>%
  drop_na(cow) %>%
  filter(
    !country_code %in% c(948, 2093),
    year %in% c(1900:2024)
  ) %>%
  dplyr::select(cow, year, pop)


# Central government debt
gov_debt_long <- read.csv("gov_debt.csv", sep = ",")
gov_debt <- reshape2::melt(gov_debt_long,
  id.vars = c("Country.Name"),
  variable.name = "year",
  value.name = "debt"
)
gov_debt$year <- gsub("X", "", as.factor(gov_debt$year))
gov_debt <- gov_debt %>%
  dplyr::mutate(cow = countrycode(Country.Name, "country.name", "cown")) %>%
  dplyr::mutate(cow = case_when(
    Country.Name == "Serbia" ~ 345,
    Country.Name == "Western Sahara" ~ 600,
    TRUE ~ cow
  )) %>%
  drop_na(cow) %>%
  filter(year %in% c(1900:2024)) %>%
  dplyr::select(cow, year, debt)

vdemdata::vdem -> vdem
vdem_vars <- vdem %>%
  dplyr::mutate(iso3c = countrycode(country_name, "country.name", "iso3c")) %>%
  dplyr::rename(cow = COWcode) %>%
  drop_na(cow) %>%
  filter(year %in% c(1900:2024)) %>%
  dplyr::select(cow, year, v2x_polyarchy, v2x_execorr)

gdp_gapminder <- read.csv("gdp_gapminder.csv", sep = ";")
gdp_gapminder <- reshape2::melt(gdp_gapminder,
  id.vars = c("geo", "Country.Name"),
  variable.name = "year",
  value.name = "value"
)
gdp_gapminder$year <- gsub("X", "", as.factor(gdp_gapminder$year))
gdp_gapminder$ISO3C <- toupper(gdp_gapminder$geo)
gdp_gapminder <- gdp_gapminder %>%
  dplyr::mutate(
    ISO3C = countrycode(ISO3C, "iso3c", "iso3c"),
    cow = countrycode(ISO3C, "iso3c", "cown")
  ) %>%
  dplyr::rename(
    iso3c = ISO3C,
    gdp_pcap = value
  ) %>%
  dplyr::mutate(cow = case_when(
    iso3c == "SRB" ~ 345,
    TRUE ~ cow
  )) %>%
  drop_na(cow) %>%
  filter(year %in% c(1945:2024)) %>%
  dplyr::select(cow, year, gdp_pcap)
gdp_gapminder <- gdp_gapminder %>%
  dplyr::mutate(gdp_pcap = as.numeric(gdp_pcap)) %>%
  arrange(cow, year) %>%
  group_by(cow) %>%
  dplyr::mutate(gdp_growth = ((gdp_pcap - dplyr::lag(gdp_pcap)) / dplyr::lag(gdp_pcap) * 100)) %>% # Compute growth rate
  ungroup()

data(popAge1dt)
youth <- popAge1dt %>%
  dplyr::mutate(cow = countrycode(name, "country.name", "cown")) %>%
  filter(!cow %in% c(948, 2093)) %>%
  filter(age >= 15) %>%
  group_by(cow, year) %>%
  dplyr::summarise(
    median_age = {
      cumulative_pop <- cumsum(pop) / sum(pop)
      ages <- age
      ages[min(which(cumulative_pop >= 0.5))]
    },
    total_15_29 = sum(pop[age >= 15 & age <= 29]),
    total_15_plus = sum(pop),
    youthbulge = total_15_29 / total_15_plus * 100
  ) %>%
  drop_na(cow) %>%
  filter(year %in% c(1950:2024)) %>%
  dplyr::select(cow, year, median_age, youthbulge)
```
```{r, merging}
df0_fisc <- state_panel(start = 1950, end = 2023, by = "year", useGW = FALSE) %>%
  dplyr::rename(cow = cowcode) %>%
  dplyr::mutate(
    country = countrycode(cow, "cown", "country.name"),
    country = ifelse(cow == 260, "German Federal Republic", country)
  )
df1_fisc <- merge(df0_fisc, population, by = c("cow", "year"), all.x = TRUE)
df2_fisc <- merge(df1_fisc, youth, by = c("cow", "year"), all.x = TRUE)
df3_fisc <- merge(df2_fisc, gdp_gapminder, by = c("cow", "year"), all.x = TRUE)
df4_fisc <- merge(df3_fisc, gov_debt, by = c("cow", "year"), all.x = TRUE)
df5_fisc <- merge(df4_fisc, vdem_vars, by = c("cow", "year"), all.x = TRUE)
df_fisc_NVC1.3_mrg <- merge(df5_fisc, NAVCO1.3_default, by = c("cow", "year"), all.x = TRUE)
df_fisc_NVC2.1_mrg <- merge(df5_fisc, NAVCO2.1_regr, by = c("cow", "year"), all.x = TRUE)
df_fisc_beis_mrg <- merge(df5_fisc, beis_regr, by = c("cow", "year"), all.x = TRUE)
df_fisc_beiscsra_mrg <- merge(df5_fisc, beis_csra, by = c("cow", "year"), all.x = TRUE)
df_fisc_nvc1.3csra_mrg <- merge(df5_fisc, nvc1.3_csra, by = c("cow", "year"), all.x = TRUE)
df_fisc_nvc2.1csra_mrg <- merge(df5_fisc, nvc2.1_csra, by = c("cow", "year"), all.x = TRUE)
```
```{r, refine datasets, include=FALSE}
df_fisc_NVC1.3 <- df_fisc_NVC1.3_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    NVC1.3_VIOL_l = dplyr::lag(NVC1.3_VIOL, n = 1),
    NVC1.3_NONVIOL_l = dplyr::lag(NVC1.3_NONVIOL, n = 1),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("NVC1.3_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_NVC1.3 %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_NVC1.3 <- df_fisc_NVC1.3 %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))

df_fisc_NVC2.1 <- df_fisc_NVC2.1_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    NVC2.1_VIOL_l = dplyr::lag(NVC2.1_VIOL, n = 1),
    NVC2.1_NONVIOL_l = dplyr::lag(NVC2.1_NONVIOL, n = 1),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("NVC2.1_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_NVC2.1 %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_NVC2.1 <- df_fisc_NVC2.1 %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))

df_fisc_beis <- df_fisc_beis_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    beis_armed_l = dplyr::lag(beis_armed, n = 1),
    beis_unarmed_l = dplyr::lag(beis_unarmed, n = 1),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("beis_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_beis %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_beis <- df_fisc_beis %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))

df_fisc_beiscsra <- df_fisc_beiscsra_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("csra_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_beiscsra %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_beiscsra <- df_fisc_beiscsra %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))

df_fisc_nvc1.3csra <- df_fisc_nvc1.3csra_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("csra_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_nvc1.3csra %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_nvc1.3csra <- df_fisc_nvc1.3csra %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))

df_fisc_nvc2.1csra <- df_fisc_nvc2.1csra_mrg %>%
  group_by(cow) %>%
  dplyr::mutate(
    gdp_pcap = log(gdp_pcap + 0.01),
    gdp_pcap_l = dplyr::lag(gdp_pcap, n = 1),
    gdp_growth_l = dplyr::lag(gdp_growth, n = 1),
    pop_log = log(pop + 0.01),
    pop_log_l = dplyr::lag(pop_log, n = 1),
    year = as.numeric(year),
    v2x_polyarchy = v2x_polyarchy + 0.01,
    v2x_polyarchy_l = dplyr::lag(v2x_polyarchy, n = 1),
    v2x_execorr_l = dplyr::lag(v2x_execorr, n = 1),
    youthbulge_l = dplyr::lag(youthbulge, n = 1),
    vdem_growth = ((v2x_polyarchy - dplyr::lag(v2x_polyarchy)) / dplyr::lag(v2x_polyarchy) * 100),
    vdem_growth_l = dplyr::lag(vdem_growth, n = 1),
    debt_l = dplyr::lag(debt, n = 1),
    log_debt = log(debt),
    log_debt_l = log(debt_l),
    debt_growth = ((debt - dplyr::lag(debt)) / dplyr::lag(debt) * 100),
    debt_growth_l = ((debt_l - dplyr::lag(debt_l)) / dplyr::lag(debt_l) * 100),
    debt_growth_mean_3y = slide_dbl(debt_growth, mean, .before = 2, .complete = TRUE),
    debt_growth_sum_3y = slide_dbl(debt_growth, sum, .before = 2, .complete = TRUE),
    period = factor(floor((year - 1950) / 10) + 1),
    region = countrycode(cow, "cown", "region")
  ) %>%
  mutate_at(
    vars(starts_with("csra_")),
    ~ replace_na(., 0)
  )

countries_2000 <- df_fisc_nvc2.1csra %>%
  filter(year == 2000, pop > 1000) %>%
  pull(cow)

df_fisc_nvc2.1csra <- df_fisc_nvc2.1csra %>%
  filter(cow %in% countries_2000 | cow %in% c(345, 315))
```

```{r, some descriptive statistics}
table(df_fisc_NVC1.3$NVC1.3_CAMPAIGN)
table(df_fisc_NVC1.3$NVC1.3_NONVIOL)
table(df_fisc_NVC1.3$NVC1.3_VIOL)

sum(is.na(df_fisc_NVC1.3$log_debt_l)) / nrow(df_fisc_NVC1.3) * 100
sum(is.na(df_fisc_NVC1.3$gdp_pcap_l)) / nrow(df_fisc_NVC1.3) * 100

df_fisc_NVC1.3[is.na(df_fisc_NVC1.3$log_debt_l) & df_fisc_NVC1.3$NVC1.3_VIOL == 1, ]

sum(length(df_fisc_NVC1.3[is.na(df_fisc_NVC1.3$log_debt_l) & is.na(df_fisc_NVC1.3$gdp_pcap_l) & df_fisc_NVC1.3$NVC1.3_VIOL == 1, ])) / sum(df_fisc_NVC1.3$NVC1.3_VIOL) # how many violent campaigns do not have information about the central government debt

sum(length(df_fisc_NVC1.3[is.na(df_fisc_NVC1.3$log_debt_l) & df_fisc_NVC1.3$NVC1.3_NONVIOL == 1, ])) / sum(df_fisc_NVC1.3$NVC1.3_NONVIOL) # how many nonviolent campaigns do not have information about the central government debt
```
```{r}
hist(df_fisc_NVC1.3$log_debt_l)
sum(length(df_fisc_NVC1.3[df_fisc_NVC1.3$log_debt_l <= 0, ]))
```



```{r, NAVCO1.3 regression (VIOL)}
m1_viol <- glm(NVC1.3_VIOL ~ log_debt_l * gdp_pcap_l,
  family = binomial(link = "logit"), method = "brglmFit", type = "MPL_Jeffreys",
  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019, ]
)
robust_m1_viol <- diag(vcovCR(m1_viol, type = "CR1S", cluster = df_fisc_NVC1.3[rownames(m1_viol$model), ]$cow))^0.5
m2_viol <- glm(NVC1.3_VIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + as.factor(region) + as.factor(period),
  family = binomial(link = "logit"), method = "brglmFit", type = "MPL_Jeffreys",
  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019, ]
)
robust_m2_viol <- diag(vcovCR(m2_viol, type = "CR1S", cluster = df_fisc_NVC1.3[rownames(m2_viol$model), ]$cow))^0.5
m3_viol <- glm(NVC1.3_VIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
  family = binomial(link = "logit"), method = "brglmFit", type = "MPL_Jeffreys",
  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019, ]
)
robust_m3_viol <- diag(vcovCR(m3_viol, type = "CR1S", cluster = df_fisc_NVC1.3[rownames(m3_viol$model), ]$cow))^0.5
m4_viol <- glm(NVC1.3_VIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
  family = binomial(link = "logit"), method = "brglmFit", type = "MPL_Jeffreys",
  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019, ]
)
robust_m4_viol <- diag(vcovCR(m4_viol, type = "CR1S", cluster = df_fisc_NVC1.3[rownames(m4_viol$model), ]$cow))^0.5
stargazer(m1_viol, m2_viol, m3_viol, m4_viol,
  type = "text",
  dep.var.labels = c("Violent campaign"),
  covariate.labels = c("Logged central government debt", "Logged GDP per capita", "GDP growth (%)", "Population", "Polyarchy score", "Polyarchy score (squared)", "Debt * GDP interaction"),
  se = list(robust_m1_viol, robust_m2_viol, robust_m3_viol, robust_m4_viol),
  notes = "Cluster-robust standard errors in parentheses. Region and period fixed effects",
  add.lines = list(c("Number of cases", sum(m1_viol$model$NVC1.3_VIOL), sum(m2_viol$model$NVC1.3_VIOL), sum(m3_viol$model$NVC1.3_VIOL), sum(m4_viol$model$NVC1.3_VIOL))),
  notes.align = "l",
  notes.label = "",
  no.space = TRUE,
  single.row = TRUE,
  omit = c("region", "cow", "period", "year")
)
```

```{r, NAVCO1.3 (NONVIOL)}
#Nonviolent
m1_nonviol <- glm(NVC1.3_NONVIOL ~ log_debt_l * gdp_pcap_l,
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019,])
robust_m1_nonviol <- diag(vcovCR(m1_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m1_nonviol$model),]$cow))^0.5
m2_nonviol <- glm(NVC1.3_NONVIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019,])
robust_m2_nonviol <- diag(vcovCR(m2_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m2_nonviol$model),]$cow))^0.5
m3_nonviol <- glm(NVC1.3_NONVIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l  + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019,])
robust_m3_nonviol <- diag(vcovCR(m3_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m3_nonviol$model),]$cow))^0.5
m4_nonviol <- glm(NVC1.3_NONVIOL ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_NVC1.3[df_fisc_NVC1.3$year >= 1950 & df_fisc_NVC1.3$year <= 2019,])
robust_m4_nonviol <- diag(vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m4_nonviol$model),]$cow))^0.5
stargazer(m1_nonviol, m2_nonviol, m3_nonviol, m4_nonviol, type = 'text',
          dep.var.labels = c('Nonviolent campaign'),
          covariate.labels = c('Logged central government debt', 'Logged GDP per capita', 'GDP growth (%)', 'Population', 'Polyarchy score', 'Polyarchy score (squared)', 'Debt * GDP interaction'),
          se = list(robust_m1_nonviol, robust_m2_nonviol, robust_m3_nonviol, robust_m4_nonviol),
          notes = 'Cluster-robust standard errors in parentheses. Region and period fixed effects',
          add.lines = list(c('Number of cases', sum(m1_nonviol$model$NVC1.3_NONVIOL), sum(m2_nonviol$model$NVC1.3_NONVIOL), sum(m3_nonviol$model$NVC1.3_NONVIOL), sum(m4_nonviol$model$NVC1.3_NONVIOL))),
          notes.align = "l",
          notes.label = '',
          no.space = TRUE,
          single.row = TRUE ,         
          omit = c('region', 'cow', 'period', 'year'))
```

```{r, visualise marginal effects between NAVCO1.3 VIOL and NONVIOL}
out_viol <- avg_predictions(m4_viol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_NVC1.3$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_NVC1.3$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                            'gdp_pcap_l' = quantile(df_fisc_NVC1.3$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m4_viol$model),]$cow))
out_viol$type <- 'Violent'

out_nonviol <- avg_predictions(m4_nonviol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_NVC1.3$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_NVC1.3$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                                  'gdp_pcap_l' = quantile(df_fisc_NVC1.3$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m4_nonviol$model),]$cow))
out_nonviol$type <- 'Nonviolent'
out_alltypes <- rbind(out_viol, out_nonviol)
ggplot(out_alltypes, aes(x = log_debt_l, y = estimate, colour = factor(gdp_pcap_l), fill = factor(gdp_pcap_l))) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + scale_colour_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) + scale_fill_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) +
  labs(x = 'Logged central government debt (exp), t-1', y = 'Estimate') + 
  facet_wrap(~type)
```
```{r, NAVCO 1.3 slopes}
slope_viol <- avg_slopes(m4_viol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beis$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beis$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                         conf_level = 0.95, vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m4_viol$model),]$cow))
slope_viol$type <- 'Violent'

slope_nonviol <- avg_slopes(m4_nonviol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beis$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beis$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                            conf_level = 0.95,  vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_NVC1.3[rownames(m4_nonviol$model),]$cow))
slope_nonviol$type <- 'Nonviolent'
names(slope_nonviol) <- names(slope_viol)
slope_alltypes <- rbind(slope_nonviol,slope_viol)
ggplot(slope_alltypes, aes(x = gdp_pcap_l, y = estimate)) + 
  geom_line() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + 
  labs(x = 'Logged GDP per capita', y = 'Estimate') +
  facet_wrap(~type)
```

```{r, Beissinger (armed)}
m1_viol <- glm(beis_armed ~ log_debt_l * gdp_pcap_l,
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m1_viol <- diag(vcovCR(m1_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m1_viol$model),]$cow))^0.5
m2_viol <- glm(beis_armed ~ log_debt_l * gdp_pcap_l + pop_log_l + gdp_growth_l + as.factor(region) + as.factor(period),
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m2_viol <- diag(vcovCR(m2_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m2_viol$model),]$cow))^0.5
m3_viol <- glm(beis_armed ~ log_debt_l * gdp_pcap_l   + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m3_viol <- diag(vcovCR(m3_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m3_viol$model),]$cow))^0.5
m4_viol <- glm(beis_armed ~ log_debt_l * gdp_pcap_l + pop_log_l + gdp_growth_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m4_viol <- diag(vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_viol$model),]$cow))^0.5
stargazer(m1_viol, m2_viol, m3_viol, m4_viol, type = 'text',
          dep.var.labels = c('Armed campaign'),
          covariate.labels = c('Logged central government debt', 'Logged GDP per capita', 'Population', 'GDP growth (%)', 'Polyarchy score', 'Polyarchy score (squared)', 'Debt * GDP interaction'),
          se = list(robust_m1_viol, robust_m2_viol, robust_m3_viol, robust_m4_viol),
          notes = 'Cluster-robust standard errors in parentheses. Region and period fixed effects',
          add.lines = list(c('Number of cases', sum(m1_viol$model$beis_armed), sum(m2_viol$model$beis_armed), sum(m3_viol$model$beis_armed), sum(m4_viol$model$beis_armed))),
          notes.align = "l",
          notes.label = '',
          no.space = TRUE,
          single.row = TRUE ,         
          omit = c('region', 'cow', 'period', 'year'))
```

```{r, Beisinger (unarmed)}
m1_nonviol <- glm(beis_unarmed ~ log_debt_l * gdp_pcap_l,
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m1_nonviol <- diag(vcovCR(m1_nonviol, type ='CR1S', cluster = df_fisc_beis[rownames(m1_nonviol$model),]$cow))^0.5
m2_nonviol <- glm(beis_unarmed ~ log_debt_l * gdp_pcap_l + pop_log_l + gdp_growth_l + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m2_nonviol <- diag(vcovCR(m2_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m2_nonviol$model),]$cow))^0.5
m3_nonviol <- glm(beis_unarmed ~ log_debt_l * gdp_pcap_l  + pop_log_l + gdp_growth_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m3_nonviol <- diag(vcovCR(m3_nonviol, type ='CR1S', cluster = df_fisc_beis[rownames(m3_nonviol$model),]$cow))^0.5
m4_nonviol <- glm(beis_unarmed ~ log_debt_l * gdp_pcap_l + gdp_growth_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_beis[df_fisc_beis$year >= 1950 & df_fisc_beis$year <= 2014,])
robust_m4_nonviol <- diag(vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_nonviol$model),]$cow))^0.5
stargazer(m1_nonviol, m2_nonviol, m3_nonviol, m4_nonviol, type = 'text',
          dep.var.labels = c('Unarmed campaign'),
          covariate.labels = c('Logged central government debt', 'Logged GDP per capita', 'GDP growth (%)', 'Population', 'Polyarchy score', 'Polyarchy score (squared)', 'Debt * GDP interaction'),
          se = list(robust_m1_nonviol, robust_m2_nonviol, robust_m3_nonviol, robust_m4_nonviol),
          notes = 'Cluster-robust standard errors in parentheses. Region and period fixed effects',
          add.lines = list(c('Number of cases', sum(m1_nonviol$model$beis_unarmed), sum(m2_nonviol$model$beis_unarmed), sum(m3_nonviol$model$beis_unarmed), sum(m4_nonviol$model$beis_unarmed))),
          notes.align = "l",
          notes.label = '',
          no.space = TRUE,
          single.row = TRUE ,         
          omit = c('region', 'cow', 'period', 'year'))
```
```{r, visualise marginal effects Beissinger armed and unarmed}
out_viol <- avg_predictions(m4_viol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_beis$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_beis$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                            'gdp_pcap_l' = quantile(df_fisc_beis$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_viol$model),]$cow))
out_viol$type <- 'Violent'

out_nonviol <- avg_predictions(m4_nonviol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_beis$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_beis$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                                  'gdp_pcap_l' = quantile(df_fisc_beis$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_nonviol$model),]$cow))
out_nonviol$type <- 'Nonviolent'
out_alltypes <- rbind(out_viol, out_nonviol)
#From 0.019 to 0.024 (рост в 1.23 раза)
ggplot(out_alltypes, aes(x = log_debt_l, y = estimate, colour = factor(gdp_pcap_l), fill = factor(gdp_pcap_l))) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + scale_colour_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) + scale_fill_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) +
  labs(x = 'Logged central government debt (exp), t-1', y = 'Estimate') + 
  facet_wrap(~type)
```
```{r, Beissinger slopes}
slope_viol <- avg_slopes(m4_viol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beis$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beis$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                         conf_level = 0.95, vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_viol$model),]$cow))
slope_viol$type <- 'Violent'

slope_nonviol <- avg_slopes(m4_nonviol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beis$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beis$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                            conf_level = 0.95,  vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beis[rownames(m4_nonviol$model),]$cow))
slope_nonviol$type <- 'Nonviolent'
names(slope_nonviol) <- names(slope_viol)
slope_alltypes <- rbind(slope_nonviol,slope_viol)
ggplot(slope_alltypes, aes(x = gdp_pcap_l, y = estimate)) + 
  geom_line() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + 
  labs(x = 'Logged GDP per capita', y = 'Estimate') +
  facet_wrap(~type)
```
```{r, NAVCO1.3 + CSRA}
m4_nonviol <- glm(csra_unarmed ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_nvc1.3csra[df_fisc_nvc1.3csra$year >= 1950 & df_fisc_nvc1.3csra$year <= 2023,])
robust_m4_nonviol <- diag(vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_nonviol$model),]$cow))^0.5

m4_viol <- glm(csra_armed ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_nvc1.3csra[df_fisc_nvc1.3csra$year >= 1950 & df_fisc_nvc1.3csra$year <= 2023,])
robust_m4_viol <- diag(vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_viol$model),]$cow))^0.5

# stargazer(m4_viol, m4_nonviol, type = 'text',
#           dep.var.labels = c('Armed campaign', 'Unarmed campaign'),
#           covariate.labels = c('Logged central government debt', 'Logged GDP per capita', 'Population', 'GDP growth (%)', 'Polyarchy score', 'Polyarchy score (squared)', 'Debt * GDP interaction'),
#           se = list(robust_m4_viol, robust_m4_nonviol),
#           notes = 'Cluster-robust standard errors in parentheses. Region and period fixed effects',
#           add.lines = list(c('Number of cases', sum(m4_viol$model$csra_armed), sum(m4_nonviol$model$csra_unarmed))),
#           notes.align = "l",
#           notes.label = '',
#           no.space = TRUE,
#           single.row = TRUE ,         
#           omit = c('region', 'cow', 'period', 'year'))

out_viol <- avg_predictions(m4_viol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_nvc1.3csra$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_nvc1.3csra$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                            'gdp_pcap_l' = quantile(df_fisc_nvc1.3csra$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_viol$model),]$cow))
out_viol$type <- 'Violent'

out_nonviol <- avg_predictions(m4_nonviol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_nvc1.3csra$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_nvc1.3csra$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                                  'gdp_pcap_l' = quantile(df_fisc_nvc1.3csra$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_nonviol$model),]$cow))
out_nonviol$type <- 'Nonviolent'
out_alltypes <- rbind(out_viol, out_nonviol)
ggplot(out_alltypes, aes(x = log_debt_l, y = estimate, colour = factor(gdp_pcap_l), fill = factor(gdp_pcap_l))) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + scale_colour_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) + scale_fill_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) +
  labs(x = 'Logged central government debt (exp), t-1', y = 'Estimate') + 
  facet_wrap(~type)
```
```{r, NAVCO1.3+CSRA slopes}
slope_viol <- avg_slopes(m4_viol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_nvc1.3csra$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_nvc1.3csra$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                         conf_level = 0.95, vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_viol$model),]$cow))
slope_viol$type <- 'Violent'

slope_nonviol <- avg_slopes(m4_nonviol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_nvc1.3csra$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_nvc1.3csra$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                            conf_level = 0.95, vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_nvc1.3csra[rownames(m4_nonviol$model),]$cow))
slope_nonviol$type <- 'Nonviolent'
names(slope_nonviol) <- names(slope_viol)
slope_alltypes <- rbind(slope_nonviol,slope_viol)
ggplot(slope_alltypes, aes(x = gdp_pcap_l, y = estimate)) + 
  geom_line() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + 
  labs(x = 'Logged GDP per capita', y = 'Estimate') +
  facet_wrap(~type)
```
```{r, Beissinger + CSRA}
m4_nonviol <- glm(csra_unarmed ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
                  family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
                  data = df_fisc_beiscsra[df_fisc_beiscsra$year >= 1950 & df_fisc_beiscsra$year <= 2023,])
robust_m4_nonviol <- diag(vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_nonviol$model),]$cow))^0.5

m4_viol <- glm(csra_armed ~ log_debt_l * gdp_pcap_l + gdp_growth_l + pop_log_l + v2x_polyarchy_l + I(v2x_polyarchy_l^2) + as.factor(region) + as.factor(period),
               family = binomial(link = 'logit'), method = "brglmFit", type = "MPL_Jeffreys",
               data = df_fisc_beiscsra[df_fisc_beiscsra$year >= 1950 & df_fisc_beiscsra$year <= 2023,])
robust_m4_viol <- diag(vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_viol$model),]$cow))^0.5

# stargazer(m4_viol, m4_nonviol, type = 'text',
#           dep.var.labels = c('Armed campaign', 'Unarmed campaign'),
#           covariate.labels = c('Logged central government debt', 'Logged GDP per capita', 'Population', 'GDP growth (%)', 'Polyarchy score', 'Polyarchy score (squared)', 'Debt * GDP interaction'),
#           se = list(robust_m4_viol, robust_m4_nonviol),
#           notes = 'Cluster-robust standard errors in parentheses. Region and period fixed effects',
#           add.lines = list(c('Number of cases', sum(m4_viol$model$csra_armed), sum(m4_nonviol$model$csra_unarmed))),
#           notes.align = "l",
#           notes.label = '',
#           no.space = TRUE,
#           single.row = TRUE ,         
#           omit = c('region', 'cow', 'period', 'year'))


out_viol <- avg_predictions(m4_viol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_beiscsra$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_beiscsra$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                            'gdp_pcap_l' = quantile(df_fisc_beiscsra$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_viol$model),]$cow))
out_viol$type <- 'Violent'

out_nonviol <- avg_predictions(m4_nonviol, by = c("log_debt_l", "gdp_pcap_l"), newdata = datagrid('log_debt_l' = seq(quantile(df_fisc_beiscsra$log_debt_l, 0.01, na.rm=TRUE), quantile(df_fisc_beiscsra$log_debt_l, 0.99, na.rm=TRUE), length.out=20),
                                                                                                  'gdp_pcap_l' = quantile(df_fisc_beiscsra$gdp_pcap_l, c(0.1, 0.9), na.rm=TRUE), grid_type = 'counterfactual'), vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_nonviol$model),]$cow))
out_nonviol$type <- 'Nonviolent'
out_alltypes <- rbind(out_viol, out_nonviol)
ggplot(out_alltypes, aes(x = log_debt_l, y = estimate, colour = factor(gdp_pcap_l), fill = factor(gdp_pcap_l))) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + scale_colour_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) + scale_fill_discrete(name = "Logged GDP per capita, t-1", labels = c('10% percentile', '90% percentile')) +
  labs(x = 'Logged central government debt (exp), t-1', y = 'Estimate') + 
  facet_wrap(~type)
```
```{r, Beissinger + CSRA slopes}
slope_viol <- avg_slopes(m4_viol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beiscsra$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beiscsra$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                         conf_level = 0.95, vcov = vcovCR(m4_viol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_viol$model),]$cow))
slope_viol$type <- 'Violent'

slope_nonviol <- avg_slopes(m4_nonviol, variables = 'log_debt_l', by = 'gdp_pcap_l', newdata = datagrid(gdp_pcap_l=seq(quantile(df_fisc_beiscsra$gdp_pcap_l, 0.05, na.rm=TRUE), quantile(df_fisc_beiscsra$gdp_pcap_l, 0.95, na.rm=TRUE), length.out=20), grid_type = 'counterfactual'),
                            conf_level = 0.95, vcov = vcovCR(m4_nonviol, type ='CR1S', cluster = df_fisc_beiscsra[rownames(m4_nonviol$model),]$cow))
slope_nonviol$type <- 'Nonviolent'
names(slope_nonviol) <- names(slope_viol)
slope_alltypes <- rbind(slope_nonviol,slope_viol)
ggplot(slope_alltypes, aes(x = gdp_pcap_l, y = estimate)) + 
  geom_line() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.1) + 
  theme_bw() + 
  labs(x = 'Logged GDP per capita', y = 'Estimate') +
  facet_wrap(~type)
```

